# Generated by Django 4.2.2 on 2023-09-28 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_is_curated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='last_drilled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collection',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
