name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu packages
        # Note: these are already installed in GitHub's Ubuntu runner image:
        run: sudo apt install build-essential libpq-dev python3-dev python3-venv
      - name: Start and configure PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo su - postgres -c "psql -c \"CREATE USER leornian WITH PASSWORD 'dbpassword';\""
          sudo su - postgres -c "psql -c \"ALTER ROLE leornian SUPERUSER;\""
      - name: Cache Python environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-lock.txt') }}
      - name: Set up Python environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
      - name: Create environment file
        run: cp .env.dist .env
      - name: Run tests
        env:
          # Override a setting from `.env.dist` that will cause test failures:
          LEOR_SECURE_SSL_REDIRECT: False
        run: venv/bin/python manage.py test --parallel=2
